name: "Testing baby"

on:
  # workflow_dispatch:
  issue_comment:
  
# jobs:
#   runner:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: setup go
#         uses: actions/setup-go@v5
#       - name: Run goreleaser
#         uses: goreleaser/goreleaser-action@v6
#         with:
#           distribution: goreleaser
#           version: 'v2.1.0'
#           args: release --clean --snapshot
#           workdir: './go'
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# jobs:
#   download:
#     runs-on: ubuntu-latest
#     steps:
#       - name: download
#         uses: actions/download-artifact@v4

# jobs:
#   buildx:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Set up Docker Buildx
#         uses: crazy-max/ghaction-docker-buildx@v3
#         with:
#           buildx-version: latest
#           qemu-version: latest

# jobs:
#   build:
#     runs-on: windows-latest
#     steps:
#     - name: configure Pagefile
#       uses: al-cheb/configure-pagefile-action@v1.4
#       with:
#         minimum-size: 8GB

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Setup mdBook
#         uses: peaceiris/actions-mdbook@v2
#         with:
#           mdbook-version: 'latest'


jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: bug
