on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Restore cached Primes
      id: cache-primes-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          primes
        key: ${{ runner.os }}-primes

    - name: Generate Prime Numbers
      if: steps.cache-primes-restore.outputs.cache-hit != 'true'
      run: ./generate-primes.sh primes

    - name: Use Prime Numbers
      run: ./print-primes.sh primes
    
    - name: Save Primes
      id: cache-primes-save
      uses: actions/cache/save@v4
      with:
        path: |
          primes
        key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}
